<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        /* thirdparties */
        'DoctrineModule',
        'DoctrineORMModule',
        'DoctrineDataFixtureModule',
        /* my application */
        'Application',
        'Backend'
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        )
    ),

    'doctrine' => array(
        'fixture' => array(
            'ModuleName_fixture' => __DIR__ . '/../src/ModuleName/Fixture',
        )
    )
);
